test: &test
  secret_key_base: 79057087c2628b1fe443ba144e13bf72d9e0e5885049b3c4d353592ec8b87cb54f034002bd1168f52f7f41e3aaed305e850c8a2bc2b961ecf8d03784c0d138b1

development:
  <<: *test
  iugu_api_key: <%= ENV['IUGU_API_KEY'] %>
  iugu_account_id: <%= ENV['IUGU_ACCOUNT_ID'] %>

production: &production
  asset_sync_gzip_compression: <%= ENV['ASSET_SYNC_GZIP_COMPRESSION'] %>
  asset_sync_manifest: <%= ENV['ASSET_SYNC_MANIFEST'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_bucket_name: <%= ENV['AWS_BUCKET_NAME'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  iugu_account_id: <%= ENV['IUGU_ACCOUNT_ID'] %>
  iugu_api_key: <%= ENV['IUGU_API_KEY'] %>
  iugu_auth_code: <%= ENV['IUGU_AUTH_CODE'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  split_password: <%= ENV['SPLIT_PASSWORD'] %>
  split_username: <%= ENV['SPLIT_USERNAME'] %>

staging:
  <<: *production
