# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12ebb4f25d25b92275e08be8e4f3c2a2e206b393315fbbd6fd8041bef769a4415830cac19803b2bae0c10d0da749fcc9f4e578ef64ac52522639831a019d6523
  iugu_api_key: <%= ENV["IUGU_API_KEY"] %>
  iugu_account_id: <%= ENV["IUGU_ACCOUNT_ID"] %>

test:
  secret_key_base: 79057087c2628b1fe443ba144e13bf72d9e0e5885049b3c4d353592ec8b87cb54f034002bd1168f52f7f41e3aaed305e850c8a2bc2b961ecf8d03784c0d138b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  aws_region: <%= ENV["AWS_REGION"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  iugu_api_key: <%= ENV["IUGU_API_KEY"] %>
  iugu_auth_code: <%= ENV["IUGU_AUTH_CODE"] %>
  iugu_account_id: <%= ENV["IUGU_ACCOUNT_ID"] %>
  asset_sync_gzip_compression: <%= ENV["ASSET_SYNC_GZIP_COMPRESSION"] %>
  asset_sync_manifest: <%= ENV["ASSET_SYNC_MANIFEST"] %>

staging:
  <<: *production
